version: '3.2'


services:

  mongo:
   image: mongo:latest
   ports: 
   - 27017:27017
  environment:
   - MONGO_INITDB_ROOT_USERNAME: development
   - MONGO_INITDB_ROOT_PASSWORD: testpassword


  mongo-express:
    ports: 
      - 8081:8081

    environment:
     - ME_CONFIG_MONGO_INITDB_USERNAME: development
     - ME_MONGO_INITDB_ROOT_USERNAME: development
     - ME_CONFIG_MONGODB_URL: mongodb+srv://1234567890:1234567890@cluster0.ezvtztl.mongodb.net/
